//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "failed_jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub uuid: String,
    #[sea_orm(column_type = "Text")]
    pub connection: String,
    #[sea_orm(column_type = "Text")]
    pub queue: String,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    #[sea_orm(column_type = "Text")]
    pub exception: String,
    pub failed_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
